[project]
name = "saltx"
version = "0.1.0"
authors = [
  { name="Thomas Hisch", email="t.hisch@gmail.com" },
]
description = "An efficient FEM based laser mode solver"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/thisch/saltx"
"Bug Tracker" = "https://github.com/thisch/saltx/issues"

[tool.pytest.ini_options]
addopts = '''
    --verbose
    -rs
    --color=yes
    --log-level=DEBUG
    --log-format="%(asctime)s.%(msecs)03d %(name)25.25s %(levelname)-8s %(message)s"
    --log-date-format="%H:%M:%S"
    --durations=100
'''

[tool.ruff]
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "I001"
]

[tool.ruff.isort]
known-first-party = ["saltx"]